.travis.yml:
  dist: xenial
  docker_defaults:
    dist: xenial
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-8
      collection: puppet5
    - set: centos-8
      collection: puppet6
    - set: debian-8
      collection: puppet5
    - set: debian-8
      collection: puppet6
    - set: debian-9
      collection: puppet5
    - set: debian-9
      collection: puppet6
    - set: debian-10
      collection: puppet5
    - set: debian-10
      collection: puppet6
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: coveralls
spec/acceptance/nodesets/centos-6.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
